apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: entrashow
    app.kubernetes.io/instance: entrashow
    app.kubernetes.io/name: httpshow
    app.kubernetes.io/version: 0.4.3
  name: entrashow
  namespace: entra
