apiVersion: v1
kind: Secret
metadata:
  labels:
    app: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/name: httpshow
    app.kubernetes.io/version: 0.4.3
  name: api
  namespace: api
stringData:
  HTTPSHOW_APP_SECRET_KEY: 84dvoCJI4ESldPtn5zfb+4ejHP1NvxD6RvI94fBk0dSQkyIYnrveqba5QITZ
  client.secret: password
